scrape_configs:
  - job_name: "online-judge-gateway"
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 3s
    static_configs:
      - targets:
          - online-judge-gateway:8080
  - job_name: "online-judge-controller"
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 3s
    dns_sd_configs:
      - names:
          - online-judge-controller
        type: A
        port: 8081
        refresh_interval: 5s
  - job_name: "online-judge-judger-master"
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 3s
    static_configs:
      - targets: 
        - online-judge-judger-master:2112
  - job_name: "online-judge-judger-worker"
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 3s
    dns_sd_configs:
      - names:
          - online-judge-judger-worker
        type: A
        port: 2112
        refresh_interval: 5s
  - job_name: "online-judge-result-collector"
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 3s
    dns_sd_configs:
      - names:
          - online-judge-result-collector
        type: A
        port: 2112
        refresh_interval: 5s
