scrape_configs:
  - job_name: "online-judge-controller"
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 3s
    dns_sd_configs:
      - names:
          - online-judge-controller
        type: A
        port: 8081
        refresh_interval: 5s
